name = "digital_twin_prezentation"
version = "0.1.0"
requires-python = ">=3.12.0"
dependencies = [
    "numpy >= 2.1.3",
    "pandas >= 2.2.3",
    "matplotlib >= 3.9.2",
    "seaborn >= 0.13.2",
    "scikit-learn >= 1.5.2",
    "sqlalchemy > 2.0.36",
    "joblib >= 1.4.2",
    "logging >= 0.4.9.6"
]