name = "digital_twin_presentation"
version = "0.1.0"
requires-python = ">=3.12.0"
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "seaborn",
    "scikit-learn",
    "sqlalchemy",
    "joblib",
    "logging"
]